import type { Recipe } from "../types/recipe"

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: "Creamy Garlic Parmesan Pasta",
    description:
      "A rich and creamy pasta dish with garlic and parmesan cheese that's perfect for a quick weeknight dinner.",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?q=80&w=500",
    category: "Italian",
    cookTime: 25,
    calories: 450,
    rating: 4.8,
    ingredients: [
      "8 oz pasta",
      "2 tbsp butter",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Cook pasta according to package instructions.",
      "In a large skillet, melt butter over medium heat.",
      "Add minced garlic and sauté until fragrant, about 1 minute.",
      "Pour in heavy cream and bring to a simmer.",
      "Add parmesan cheese and stir until melted and sauce is smooth.",
      "Season with salt and pepper to taste.",
      "Add cooked pasta to the sauce and toss to coat.",
      "Garnish with fresh parsley before serving.",
    ],
  },
  {
    id: 2,
    title: "Spicy Thai Basil Chicken",
    description: "A flavorful and spicy Thai dish that comes together in minutes. Perfect served over steamed rice.",
    imageUrl: "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?q=80&w=500",
    category: "Asian",
    cookTime: 20,
    calories: 380,
    rating: 4.7,
    ingredients: [
      "1 lb ground chicken",
      "4 cloves garlic, minced",
      "2 Thai chili peppers, sliced",
      "1 tbsp oil",
      "2 tbsp soy sauce",
      "1 tbsp fish sauce",
      "1 tsp sugar",
      "1 cup Thai basil leaves",
      "Steamed rice for serving",
    ],
    instructions: [
      "Heat oil in a wok or large skillet over high heat.",
      "Add minced garlic and chili peppers, stir-fry for 30 seconds.",
      "Add ground chicken and cook until browned, breaking it up as it cooks.",
      "Mix soy sauce, fish sauce, and sugar in a small bowl, then pour over the chicken.",
      "Cook for another 2 minutes until the sauce is absorbed.",
      "Turn off the heat and stir in the Thai basil leaves until wilted.",
      "Serve hot over steamed rice.",
    ],
  },
  {
    id: 3,
    title: "Avocado & Quinoa Bowl",
    description: "A nutritious and filling bowl packed with protein and healthy fats. Perfect for meal prep!",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=500",
    category: "Vegetarian",
    cookTime: 30,
    calories: 420,
    rating: 4.5,
    ingredients: [
      "1 cup quinoa",
      "2 cups vegetable broth",
      "1 avocado, sliced",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, diced",
      "1/4 cup red onion, diced",
      "2 tbsp olive oil",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Rinse quinoa under cold water.",
      "In a medium saucepan, combine quinoa and vegetable broth.",
      "Bring to a boil, then reduce heat to low, cover, and simmer for 15 minutes.",
      "Remove from heat and let stand for 5 minutes, then fluff with a fork.",
      "In a large bowl, combine cooked quinoa, tomatoes, cucumber, and red onion.",
      "Whisk together olive oil, lemon juice, salt, and pepper.",
      "Pour dressing over the quinoa mixture and toss to combine.",
      "Top with sliced avocado and fresh cilantro before serving.",
    ],
  },
  {
    id: 4,
    title: "Classic Beef Burger",
    description: "A juicy homemade beef burger with all the fixings. Perfect for summer barbecues!",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=500",
    category: "American",
    cookTime: 25,
    calories: 650,
    rating: 4.9,
    ingredients: [
      "1 lb ground beef",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "1 tsp Worcestershire sauce",
      "4 burger buns",
      "4 slices cheese",
      "Lettuce, tomato, onion for serving",
      "Ketchup, mustard, mayo for serving",
    ],
    instructions: [
      "In a bowl, combine ground beef, salt, pepper, and Worcestershire sauce.",
      "Divide the mixture into 4 equal portions and form into patties.",
      "Heat a grill or skillet over medium-high heat.",
      "Cook the patties for 4-5 minutes per side for medium doneness.",
      "Add cheese slices during the last minute of cooking to melt.",
      "Toast the burger buns lightly.",
      "Assemble burgers with desired toppings and condiments.",
    ],
  },
  {
    id: 5,
    title: "Mediterranean Chickpea Salad",
    description: "A refreshing and protein-packed salad with Mediterranean flavors. Great for lunch or as a side dish.",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=500",
    category: "Mediterranean",
    cookTime: 15,
    calories: 320,
    rating: 4.6,
    ingredients: [
      "2 cans chickpeas, drained and rinsed",
      "1 cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/2 red onion, finely diced",
      "1/2 cup feta cheese, crumbled",
      "1/4 cup kalamata olives, sliced",
      "3 tbsp olive oil",
      "2 tbsp lemon juice",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
      "Fresh parsley, chopped",
    ],
    instructions: [
      "In a large bowl, combine chickpeas, cucumber, tomatoes, red onion, feta cheese, and olives.",
      "In a small bowl, whisk together olive oil, lemon juice, oregano, salt, and pepper.",
      "Pour the dressing over the salad and toss to combine.",
      "Garnish with fresh parsley before serving.",
      "For best flavor, refrigerate for at least 30 minutes before serving.",
    ],
  },
  {
    id: 6,
    title: "Chocolate Chip Cookies",
    description: "Classic homemade chocolate chip cookies that are soft in the middle and crispy on the edges.",
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=500",
    category: "Dessert",
    cookTime: 25,
    calories: 180,
    rating: 4.9,
    ingredients: [
      "1 cup butter, softened",
      "3/4 cup granulated sugar",
      "3/4 cup brown sugar, packed",
      "2 eggs",
      "2 tsp vanilla extract",
      "2 1/4 cups all-purpose flour",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "2 cups chocolate chips",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "In a large bowl, cream together butter, granulated sugar, and brown sugar until smooth.",
      "Beat in eggs one at a time, then stir in vanilla.",
      "In a separate bowl, combine flour, baking soda, and salt.",
      "Gradually add dry ingredients to the wet ingredients and mix well.",
      "Fold in chocolate chips.",
      "Drop by rounded tablespoons onto ungreased baking sheets.",
      "Bake for 9-11 minutes or until golden brown.",
      "Allow cookies to cool on baking sheet for 2 minutes before transferring to wire racks.",
    ],
  },
  {
    id: 7,
    title: "Vegetable Stir Fry",
    description: "A quick and healthy vegetable stir fry with a flavorful sauce. Ready in just 15 minutes!",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=500",
    category: "Asian",
    cookTime: 15,
    calories: 250,
    rating: 4.4,
    ingredients: [
      "2 tbsp vegetable oil",
      "2 cloves garlic, minced",
      "1 tbsp ginger, minced",
      "1 bell pepper, sliced",
      "1 cup broccoli florets",
      "1 carrot, julienned",
      "1 cup snap peas",
      "1 cup mushrooms, sliced",
      "2 tbsp soy sauce",
      "1 tbsp hoisin sauce",
      "1 tsp sesame oil",
      "Green onions for garnish",
    ],
    instructions: [
      "Heat vegetable oil in a wok or large skillet over high heat.",
      "Add garlic and ginger, stir-fry for 30 seconds until fragrant.",
      "Add vegetables, starting with the ones that take longer to cook (broccoli, carrots).",
      "Stir-fry for 3-4 minutes, then add the remaining vegetables.",
      "Continue cooking for another 2-3 minutes until vegetables are crisp-tender.",
      "In a small bowl, mix soy sauce and hoisin sauce, then pour over vegetables.",
      "Toss to coat and cook for another minute.",
      "Drizzle with sesame oil and garnish with green onions before serving.",
    ],
  },
  {
    id: 8,
    title: "Banana Oatmeal Smoothie",
    description:
      "A filling breakfast smoothie packed with oats, banana, and protein to keep you energized all morning.",
    imageUrl: "https://images.unsplash.com/photo-1577805947697-89e18249d767?q=80&w=500",
    category: "Breakfast",
    cookTime: 5,
    calories: 280,
    rating: 4.7,
    ingredients: [
      "1 ripe banana",
      "1/2 cup rolled oats",
      "1 cup milk (dairy or plant-based)",
      "1 tbsp honey or maple syrup",
      "1 tbsp peanut butter",
      "1/2 tsp cinnamon",
      "1/2 cup ice cubes",
      "Optional: 1 scoop protein powder",
    ],
    instructions: [
      "Add all ingredients to a blender.",
      "Blend on high speed until smooth and creamy, about 1 minute.",
      "If the smoothie is too thick, add more milk to reach desired consistency.",
      "Pour into a glass and enjoy immediately.",
    ],
  },
  {
    id: 9,
    title: "Margherita Pizza",
    description: "A classic Italian pizza with a simple tomato sauce, fresh mozzarella, and basil leaves.",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=500",
    category: "Italian",
    cookTime: 35,
    calories: 550,
    rating: 4.8,
    ingredients: [
      "1 pizza dough",
      "1/2 cup tomato sauce",
      "8 oz fresh mozzarella, sliced",
      "Fresh basil leaves",
      "2 tbsp olive oil",
      "Salt to taste",
      "Red pepper flakes (optional)",
    ],
    instructions: [
      "Preheat oven to 475°F (245°C) with a pizza stone if available.",
      "Roll out the pizza dough on a floured surface to desired thickness.",
      "Spread tomato sauce evenly over the dough, leaving a small border for the crust.",
      "Arrange mozzarella slices on top of the sauce.",
      "Bake for 10-12 minutes, or until the crust is golden and the cheese is bubbly.",
      "Remove from oven and immediately top with fresh basil leaves.",
      "Drizzle with olive oil, sprinkle with salt, and add red pepper flakes if desired.",
      "Slice and serve hot.",
    ],
  },
  {
    id: 10,
    title: "Grilled Salmon with Lemon",
    description: "Perfectly grilled salmon with a simple lemon and herb seasoning. Healthy and delicious!",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=500",
    category: "Seafood",
    cookTime: 20,
    calories: 320,
    rating: 4.9,
    ingredients: [
      "4 salmon fillets (6 oz each)",
      "2 tbsp olive oil",
      "2 cloves garlic, minced",
      "1 lemon, thinly sliced",
      "1 tbsp fresh dill, chopped",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "Lemon wedges for serving",
    ],
    instructions: [
      "Preheat grill to medium-high heat.",
      "In a small bowl, mix olive oil and minced garlic.",
      "Pat salmon fillets dry with paper towels.",
      "Brush both sides of salmon with the garlic oil mixture.",
      "Season with salt and pepper.",
      "Place salmon skin-side down on the grill.",
      "Top each fillet with lemon slices and sprinkle with dill.",
      "Grill for 4-6 minutes per side, or until fish flakes easily with a fork.",
      "Serve with additional lemon wedges.",
    ],
  },
]
